M48
; DRILL file {KiCad (6.0.4)} date Sat May  7 21:30:56 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-07T21:30:56+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X134.1Y-27.96
X161.9Y-27.96
T2
X108.0Y-24.41
X108.0Y-64.41
X188.0Y-24.41
X188.0Y-64.41
T0
M30
